#print('hello world!')
#print("Hello Humna")
#print("Day 1 - String Manipulation")
#print("String Concatenation is done with the '+' sign.")
#print('e.g. print("Hello " + "world")')
#print("New lines can be created with a backslash and n.")
#input("What is your name?")
# print("Hello " + input("What is your name?\n"))
str=input("What is you name?\n")
print("I will tell you number of characters in your name!")
print(len(str))
